Repository mainmatter/ember-test-selectors, pull requests merged in 2019-03, with the labels that each got.

#337 Drop support for Node.js 4 and 6
  .travis.yml
  package.json
Labels: breaking

#338 Use `setupPreprocessorRegistry()` hook to register HTMLBars AST plugin
  README.md
  index.js
Labels: breaking

#339 Enable parallel file processing for `ember-cli-babel`
  ember-cli-build.js
  index.js
Labels: enhancement

#323 Handle components with empty tag name
  README.md
  addon/utils/bind-data-test-attributes.js
  node-tests/fixtures/default/expected.js
  node-tests/fixtures/default/expected6.js
  node-tests/fixtures/default/expected7.js
  node-tests/fixtures/default/fixture.js
  strip-data-test-properties-plugin.js
  strip-data-test-properties-plugin6.js
  tests/acceptance/bind-data-test-attributes-in-components-test.js
  tests/dummy/app/components/tagless-component.js
  tests/dummy/app/templates/bind-test.hbs
  tests/dummy/app/templates/components/tagless-component.hbs
  tests/unit/utils/bind-data-test-attributes-test.js
Labels: enhancement

#341 Adjust Ember.js support range to 2.16+
  README.md
  package.json
Labels: breaking

#340 Adjust `.npmignore` blacklist
  .npmignore
Labels: internal

#342 README: Add Node.js compatibility information
  README.md
Labels: documentation
