Repository mainmatter/ember-test-selectors, pull requests merged in 2021-07, with the labels that each got.

#752 Deprecate ember-cli-babel v5.x support
  index.js
Labels: enhancement

#753 Remove obsolete `greenkeeper` configuration
  package.json
Labels: internal

#751 Deprecate `TransformTestSelectorParamsToHashPairs` transform
  transform-test-selector-params-to-hash-pairs.js
Labels: enhancement

#755 README: Remove outdated EmberMap video
  README.md
Labels: documentation

#758 Remove deprecated `TransformTestSelectorParamsToHashPairs` transform
  index.js
  tests/acceptance/bind-data-test-attributes-in-components-test.js
  tests/dummy/app/controllers/bind-test.js
  tests/dummy/app/templates/bind-test.hbs
  tests/dummy/app/version-checks.js
  tests/integration/strip-data-test-attributes-from-components-test.js
  transform-test-selector-params-to-hash-pairs.js
Labels: breaking

#759 Stop testing on non-LTS Ember releases before v3.24
  package.json
Labels: breaking

#757 Remove support for ember-cli-babel v5
  index.js
  node-tests/fixtures/default/expected.js
  node-tests/multidep.json
  node-tests/strip-data-test-properties-plugin-test.js
  strip-data-test-properties-plugin.js
Labels: breaking

#763 Remove `multidep` setup
  node-tests/fixtures/default/expected6.js
  node-tests/multidep.json
  node-tests/strip-data-test-properties-plugin-test.js
  package.json
  yarn.lock
Labels: internal

#756 Drop support for Node.js 10
  .github/workflows/ci.yml
  .github/workflows/release.yml
  package.json
Labels: breaking

#764 Remove deprecated automatic attribute binding
  README.md
  addon/utils/bind-data-test-attributes.js
  index.js
  tests/acceptance/bind-data-test-attributes-in-components-test.js
  tests/dummy/app/templates/bind-test.hbs
  tests/unit/utils/bind-data-test-attributes-test.js
  vendor/ember-test-selectors/patch-component.js
Labels: breaking

#761 CI: Use new yarn cache in `setup-node` action
  .github/workflows/ci.yml
Labels: internal
