Repository mainmatter/ember-test-selectors, pull requests merged in 2024-07, with the labels that each got.

#1256 CI: Disable floating Ember.js test scenarios
  .github/workflows/ci.yml
Labels: internal

#1257 CI: Add Node.js 18 and 20 to the test matrix
  .github/workflows/ci.yml
Labels: internal

#1258 Remove support for Node.js 12, 14 and 16
  .github/workflows/ci.yml
  .github/workflows/release.yml
  package.json
Labels: breaking

#1220 Remove Glimmer AST Deprecation
  strip-test-selectors.js
Labels: enhancement
